name: Deploy Container App

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: nodeapp-container

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log into GitHub Container Registry
      uses: docker/login-action@v3
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
          images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      id: push 
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64

    outputs: 
      repo_digest: "ghcr.io/${{ github.repository }}@${{ steps.push.outputs.digest }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
              
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        
    - name: Set Registry Auth
      uses: Azure/appservice-settings@v1
      with:
       app-name: nodeapp-container
       app-settings-json: |
         [
             {
                 "name": "DOCKER_REGISTRY_SERVER_URL",
                 "value": "https://ghcr.io",
                 "slotSetting": false
             },
             {
                 "name": "DOCKER_REGISTRY_SERVER_USERNAME",
                 "value": "${{ github.repository_owner }}",
                 "slotSetting": false
             },
             {
                 "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
                 "value": "${{ secrets.REGISTRY_PASSWORD }}",
                 "slotSetting": false
             }
         ]
    
    - name: Deploy to Azure Web App Container
      uses: azure/webapps-deploy@v3
      with:
       app-name: ${{ env.AZURE_WEBAPP_NAME }}
